name: Fetch All Products
on:
  #  schedule:
  #    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build project
        run: npm run build
      - name: Fetch all products
        run: node dist/fetch-all.js
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            output
            debug          
